# Resources/config/services.yml
parameters:
    my_admin_bundle.show_user_listener.class: Test1Bundle\EventListener\MyShowUserListener
    my_admin_bundle.menu_listener.class: Test1Bundle\EventListener\MyMenuItemListListener

services:
    my_admin_bundle.show_user_listener:
        class: %my_admin_bundle.show_user_listener.class%
        arguments:
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }
            - { name: kernel.event_listener, event: theme.sidebar_user, method: onShowUser }

    my_admin_bundle.menu_listener:
        class: %my_admin_bundle.menu_listener.class%
        tags:
            - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }

    # BEGIN managers
    manager.company:
        class: Test1Bundle\Entity\Manager\CompanyManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@repository.company"
    # END managers

    # BEGIN Repository
    repository.company:
        class: Test1Bundle\Entity\Repository\CompanyRepository
        factory: [ "@doctrine.orm.entity_manager", getRepository ]
        arguments: [Test1Bundle\Entity\Company]
    # END Repository