services:
   controller.company:
        class: AppBundle\Controller\CompanyController
        arguments:
          - '@translator.default'
          - '@manager.company'
   controller.comment:
        class: AppBundle\Controller\CommentController
