services:
    manager.company:
        class: AppBundle\Entity\Manager\CompanyManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@repository.company"

    manager.comment:
        class: AppBundle\Entity\Manager\CommentManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@repository.comment"
