test1_user:
    resource: "@Test1Bundle/Controller/UserController.php"
    type:     annotation

test1:
    resource: "@Test1Bundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

jmose_command_scheduler:
    resource: "@JMoseCommandSchedulerBundle/Resources/config/routing.yml"
    prefix:   /