# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Test1Bundle\Entity\User:
            algorithm: bcrypt
    providers:
        our_db_provider:
            entity:
                class: Test1Bundle:User

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
#        login_firewall:
#            pattern:   ^/login$
#            anonymous: ~
#        secured_area:
#            pattern:    ^/
#            form_login: ~
        main:
            anonymous: ~
            form_login:
                login_path: login
                check_path: login

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_ADMIN }