parameters:
    my_user_provider.class: AppBundle\Security\Core\User\FOSUBUserProvider

services:
    rabbit_api_call_queue:
        class: Test1Bundle\Adapters\RabbitQueueProducer
        arguments: ["@old_sound_rabbit_mq.api_call_producer"]

    rabbit_make_api_call:
        class: Test1Bundle\Adapters\RabbitQueueConsumer

    my_user_provider:
        class: "%my_user_provider.class%"
        arguments:
            - '@fos_user.user_manager'
            - {facebook: facebook_id, google: google_id}
