# Companies routing (routing defined in controller):
company_index:
    path: "/"
    defaults: {_controller: "controller.company:indexAction"}
    methods: ["GET"]
#    requirements:
#        inventoryId: '\d+'

company_add:
    path: "/add"
    defaults: {_controller: "controller.company:newAction"}
    methods: ["GET", "POST"]

company_edit:
    path: "/edit/{entity}"
    defaults: {_controller: "controller.company:editAction"}
    methods: ["GET", "POST"]

company_view:
    path: "/view/{entity}"
    defaults: {_controller: "controller.company:showAction"}
    methods: ["GET"]

company_delete:
    path: "/delete/{entity}"
    defaults: {_controller: "controller.company:deleteAction"}
    methods: ["POST"]
