# Comments routing (routing defined in controller):
comments:
    resource: "@AppBundle/Controller/CommentController.php"
    type:     annotation

# Companies routing (routing defined in controller):
companies:
    resource: "@AppBundle/Controller/CompanyController.php"
    type:     annotation

# Rabbit routing (routing defined in controller):
rabbit_producer_test_1:
    resource: "@AppBundle/Controller/RabbitProducerTest1Controller.php"
    type:     annotation

# Users routing (routing defined in controller):
users:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation
