parameters:
    my_admin_bundle.show_user_listener.class: AppBundle\EventListener\MyShowUserListener
    my_admin_bundle.menu_listener.class: AppBundle\EventListener\MyMenuItemListListener
    my_user_provider.class: AppBundle\Security\Core\User\FOSUBUserProvider

services:
    my_user_provider:
        class: "%my_user_provider.class%"
        arguments:
            - '@fos_user.user_manager'
            - {facebook: facebook_id, google: google_id}

    my_admin_bundle.show_user_listener:
        class: "%my_admin_bundle.show_user_listener.class%"
        arguments:
            - "@security.token_storage"
        tags:
            - { name: kernel.event_listener, event: theme.navbar_user, method: onShowUser }
            - { name: kernel.event_listener, event: theme.sidebar_user, method: onShowUser }

    my_admin_bundle.menu_listener:
        class: "%my_admin_bundle.menu_listener.class%"
        arguments:
            - "@security.authorization_checker"
        tags:
            - { name: kernel.event_listener, event:theme.sidebar_setup_menu, method:onSetupMenu }

    # BEGIN managers
    manager.company:
        class: AppBundle\Entity\Manager\CompanyManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@repository.company"
    # END managers

    # BEGIN Repository
    repository.company:
        class: AppBundle\Entity\Repository\CompanyRepository
        factory: [ "@doctrine.orm.entity_manager", getRepository ]
        arguments: [Test1Bundle\Entity\Company]
    # END Repository

